### PR TITLE
Fixed missile legacy targeting attempting to use the newer systems.

### PR DESCRIPTION
**Pull request by Yskinator**
Fixed legacy targeted missiles trying to call Update[TargetingType]Target() functions due to what should have been an else-if being an if.

### CODE REVIEW

**Comment by BahamutoD** [comment]
I'm denying this because missiles under legacy targeting still need to be able to acquire flares or be affected by chaff/ecm, which is updated in the other methods, although since UpdateLegacyTarget keeps overwriting the heat/radar target, something else needs to be done to let it know if the lock on the original target vessel has been broken.

**Comment by Yskinator** [comment]
Would it be better to have a legacy targeting check at the beginning of those Update[TargetingType]Target() methods, deal with the countermeasures there, and leave the function before it tries to use the new targeting system and runs into null refs, or would you prefer to add the countermeasure logic inside UpdateLegacyTarget()? Whichever you prefer, I'll see if I can add it later today.

**Comment by Yskinator** [comment]
Looking at the current CM code, it can't really be used as is with legacy targeting, so I dug up some of your old flare code and made it work with the current version. I'll see if I can make something similar for the other counter measures, and then call that from UpdateLegacyTarget().

Does that sound about right, or do you want me to do something else or leave it alone for now?

**Comment by Yskinator** [comment]
UpdateLegacyTarget() now uses the old flare logic for flares. Still need to do the other countermeasures though.

**Comment by BahamutoD** [comment]
Just leave it for now.  What I want for legacy targeting is to just give
the missile the data it needs on launch or in flight for the new targeting
to work.  That way we don't need to worry about two different systems all
the time.

**Comment by Yskinator** [comment]
Alright. I'll get back to blowing things up in space then :)

**Comment by Yskinator** [comment]
BahamutoD's superior fixes will be used instead.

**Pull request closed without merging**
