### PR TITLE
Bullet Drag, Damage and Penetration Changes

### PR DESCRIPTION
**Pull request by ferram4**
This includes changes in bullet performance to make them behave more realistically and provide reasons (for other mods) to choose between different caliber weapons when set up correctly:
- Bullet damage is no based on energy at impact, not momentum.  This requires changing the default damage multiplier for bullets, recommend somewhere between 100 and 250.
- Bullet penetration based on angle is now guaranteed >~75 degrees impact angle, and ricochets are guaranteed <~5 degrees.
- Bullet penetration also based on velocity at impact; <340 m/s bullets have greater chance of ricochet
- Two bullet drag models to choose from, or disable drag:
1. No drag, same as current system.
2. Analytic Estimate.  Calculates change in drag based on flight time, bullet drag area (assumed constant, no variation with velocity) and mass at impact.  Cheap, relatively accurate for bullets in flat trajectory.  Arcing or downward / upward firing trajectories are less accurate.  Doesn't affect trajectory, only velocity (and thus, damage) at impact.  Set as default and is easiest for AI to use.
3. Numerical Integration.  Calculates change in velocity with timestep.  Most accurate, affects trajectory (note: trajectory predictions do not account for this).  Inaccurate for AI unless at very close distances.  Best for howitzers, mortars, tank cannons, etc.

These changes should be valuable for BDArmory add-on mods that provide other types of weapons to work with.  Should allow greater differentiation between the effects of different calibers while still providing (with analytic estimate) a cheap and simple way for the AI to make use of the weapons and compensate for gravity.

### CODE REVIEW

**Comment by BahamutoD** [comment]
Awesome, thank you!  I'll see about merging this tomorrow.  Since I have a whole bunch of changes on my local version that I haven't committed yet, I assume I can just commit them first and then merge this?

**Comment by ferram4** [comment]
Sure, if those commits break the auto-merge then ping here and I'll make the changes necessary so that it can be auto-merged.

**Comment by BahamutoD** [comment]
Alright, it's up to date but it looks like it broke auto-merge.  The conflicts should be very minor though.

**Comment by ferram4** [comment]
Alright, that should be it.  Turned out the only conflicts were the dlls.

As a note: when you release, do make sure to switch the configuration from debug to release.  It does result in some minor performance improvements from the compiler.  It's not much, but it still helps.

**Comment by BahamutoD** [comment]
Ah, I didn't know that! Thanks!

**Pull request merged**
