### PR TITLE
G-Limiting and Dynamic Min Altitude

### PR DESCRIPTION
**Pull request by ferram4**
Adds a simple G-limiting feature to the AI pilot to prevent structural failures during very high dynamic pressure maneuvers.  Works by calculating the vessel acceleration in the pitch plane and relating that to vehicle pitch angle of attack; AoA limits are then set based on the projected acceleration assuming forces scale with dynamic pressure.  Pitch input limits are then searched for to prevent the AI from exceeding chosen G forces (by much, it's a soft limit).

Since this can lead to a craft not being capable of pulling out of a dive before smacking into the ground, the altitude necessary to pull out of a dive is estimated based on a combination of G limits, maximum lift acceleration possible (at that dynamic pressure), current airspeed and dive angle to add an extra buffer to command a pull out.  Still won't save it in maneuvers around the mountains, but will help everywhere else.

Due to the way this is coded, none of it is reliant on stock or FAR aerodynamics; it'll make use of whatever's thrown at it.  The pure dynamic pressure variation (with no Mach number considerations) does result in some deviations as Mach number varies, but these are minor.

@BahamutoD, so, there are design decisions here as well.  The current G limit is hardcoded at 5 for demonstration purposes, but this is clearly something that should be configurable.  I know you're of the opinion that adding more to the right-click menus is messy and silly, so what do you wanna do here?

Also, another decision: dynamic min altitude adjustment; should it add on top of the current min altitude setting (so, a craft with a min alt of 600 m should endeavor to pull out of the dive with 600 m to spare) or should it pick whichever of the two is higher (so only attempt pull-out above 600 m if it needs more than 600m to pull out)?

Whatever you want, I'll look into putting into this PR.

### CODE REVIEW

**Comment by BahamutoD** [comment]
Very cool, again. Thanks!
As for the configurable variables, I'll eventually want to have a nice GUI popup (or as a module in the weapon manager) for it, but for now, temporarily adding more sliders to the right-click menu will be fine.

As for the min altitude, I think the latter option sounds good.

I shall go test this out now!

**Comment by BahamutoD** [comment]
By the way, would it be easy to use this to force a user-selected AoA limit?

**Comment by ferram4** [comment]
That could be modified in.  Currently it searches for the upper / lower AoA limits that it can handle (based on acceleration at previous AoAs) and then adjusts the allowable pitch input limits to limit that.  Adding a user-input AoA max / min would be easy enough, but it will still have the same "soft" limit behavior as the current limits.  Then again, I suspect that if minor overshoots are a problem then increasing the steer damping on a particular vehicle should be enough.

**Comment by ferram4** [comment]
There's an attempt at adding the AoA limit in there, setting the g limit, and changes to the dynamic min altitude in there.  Still not happy with it because I'm having difficulty limiting the initial maneuver gs.

**Comment by ferram4** [comment]
@BahamutoD so I think it's about as good as it can be right now.  Depending on the steerdamping value, it can still over-g on the initial maneuver, but it will drop it to something reasonable quickly and definitely reduces the peak over-g in any case.  MaxAoA seems somewhat less effective, but that's the way these things work.

I also made the turn radius and max acceleration from lift publicly available through properties for future use.  They should allow the AI pilots to be made aware of whether they can turnfight a particular enemy at a given speed and decide whether to extend away (in the case where they can't turn with it) or to continue to push through a turn.

**Comment by BahamutoD** [comment]
I did some quick tests using FAR, and found that during a standard idle orbit, after about 10-20 seconds into the orbit, the G-limiter debug labels would disappear (I guess it didn't make it past this block: https://github.com/BahamutoD/BDArmory/pull/17/files#diff-1986a98da9ecf348b2c1d985a0847bbaR956 ) And after a few moments, it would return, but the pitch limits would be extremely low, like 0.01 to 0.1, so the AI would barely pull and the plane eventually dives down into the ocean.  The airspeed was well above take off velocity, so something was causing gaoASlopePerDynPres == 0.  I haven't fully wrapped my brain around how everything works so I'm not sure where to look to solve this.  Any ideas?

**Comment by ferram4** [comment]
That block is only there to prevent funky behavior below takeoff speed, so that should only come into play if the plane is under-engined or climbing too aggressively and drops below takeoff speed.  The other option shouldn't come into play unless the plane has been tumbling severely just prior to that, where it might get positive gs at a negative AoA and negative gs at a positive AoA.

The other over-limiting behavior got fixed a few commits ago, and I haven't been able to reproduce it again.  Normally seems to have been caused by planes that can end up with pitch-down inputs being required at very high speeds, but the current adjustments to ensure that the limits are changed very fast if the current control limit is near the limit should take care of that...

If it's still happening with the latest commits, then the thing to look into is this block and the one after it: https://github.com/BahamutoD/BDArmory/pull/17/files#diff-1986a98da9ecf348b2c1d985a0847bbaR922.  They adjust the limits as needed once the control input is far enough from the center of the limited region (so it doesn't adjust either limit if the control input is only 15% of the way towards either limit, but does otherwise).  You could try re-adding entry to those blocks based on the pitch-input scalars, but when doing that the limits can be pushed up really fast if the vehicle has a really high steer factor (due to the controller pushing the pitch inputs all over the place, particularly during aiming).

**Comment by BahamutoD** [comment]
Hey ferram4, it seems I broke the auto merge again.  I'm ready to give this a real shot now, so once you get a chance, please take a look. Thanks!

**Comment by ferram4** [comment]
Alright, so I fixed the auto-merge, that wasn't too difficult.

So, there is one thing that requires some testing with this: how it handles vehicles with a notable pitch-up/pitch-down tendency at 0 AoA (or, from another perspective, vehicles where their 0-control-input orientation is not 0 AoA).  It is possible that there can be some weirdness with the behavior of those, but that's the only possible issue remaining that I can think of.

**Comment by BahamutoD** [comment]
So I tested it in stock aero first, and I was still consistently getting unnecessary limiting even with a plane that had 0 AoA at 0 input.  It was most noticeable when I set Max G to 25, and it would only pull 2 or 3 G's.  This was right after take-off and entering the first turn towards a target at 6o'clock.

At the default of 10g's this didn't happen right away, but sometime eventually later.

PS sorry for continuously breaking the merge..

**Comment by ferram4** [comment]
Was it overlimited from the start, or did it happen after a severe high-g maneuver that broke past the limits that it should have passed?

**Comment by BahamutoD** [comment]
Here's a video showing what happens: https://www.youtube.com/watch?v=5QXVwrJRuLM

**Comment by ferram4** [comment]
So, it looks like in the beginning it's simply not adjusting things properly.  Probably has something to do with the large gimbal range of the engines, though I can look at trying to adjust that to make more sense.   The rest seems approximately okay, and the large amount of roll-left, roll-right madness trying to get a shot near the end makes me think that behavior at that point was still perfectly fine.

I'll see what I can do.

**Comment by BahamutoD** [comment]
I had the gimbals turned off on this plane though.  It seemed to only happen during a take-off.  When I turn off and turn back on the autopilot while it's already in flight, it looks like it works fine.

**Comment by ferram4** [comment]
Alright, so I added a bit of code to the g limiter, if it's limiting it will check the current vehicle pitch g's to see if they are near the limit first and while it will still limit, it will boost the integrator for the next frame.  Should fix the issue.

**Pull request merged**
